name: Template Git Actions

on:
  pull_request:
    branches:
      - main

jobs:
  base-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Prettier
        run: yarn format:ci

      - name: Run ESLint
        run: yarn lint

      - name: Run Typescript
        run: yarn typescript:ci

      - name: Build the application
        run: yarn build
